// <auto-generated />
using System;
using AracIlan.Altyapi.Veritabani;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AracIlan.Altyapi.Migrations
{
    [DbContext(typeof(AracIlanVeritabani))]
    [Migration("20260313090025_IlkMigration")]
    partial class IlkMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AracIlan.Alan.Varliklar.Arac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("HasarDurumu")
                        .HasColumnType("int");

                    b.Property<DateTime?>("IlanBitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("IlanDurumu")
                        .HasColumnType("int");

                    b.Property<int>("Kategori")
                        .HasColumnType("int");

                    b.Property<int>("Kilometre")
                        .HasColumnType("int");

                    b.Property<string>("KullaniciId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MotorSecenegiId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Renk")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.Property<string>("TeknikOzelliklerJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UretimYili")
                        .HasColumnType("int");

                    b.Property<string>("VitesTipi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MotorSecenegiId");

                    b.ToTable("Araclar", (string)null);
                });

            modelBuilder.Entity("AracIlan.Alan.Varliklar.AracGorseli", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AracId")
                        .HasColumnType("int");

                    b.Property<string>("DosyaYolu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.Property<int>("Sira")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AracId");

                    b.ToTable("AracGorselleri", (string)null);
                });

            modelBuilder.Entity("AracIlan.Alan.Varliklar.ExpertizRaporu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AIAnalizSonucu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AracId")
                        .HasColumnType("int");

                    b.Property<string>("GorselYolu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AracId")
                        .IsUnique();

                    b.ToTable("ExpertizRaporlari", (string)null);
                });

            modelBuilder.Entity("AracIlan.Alan.Varliklar.KullaniciAboneligi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("KullaniciId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KullanilanIlanHakki")
                        .HasColumnType("int");

                    b.Property<string>("OdemeReferansi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.Property<int>("UyelikPaketiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UyelikPaketiId");

                    b.ToTable("KullaniciAbonelikleri", (string)null);
                });

            modelBuilder.Entity("AracIlan.Alan.Varliklar.Marka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("Kategori")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.Property<int>("Sira")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Markalar", (string)null);
                });

            modelBuilder.Entity("AracIlan.Alan.Varliklar.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("MarkaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UretimBaslangicYili")
                        .HasColumnType("int");

                    b.Property<int>("UretimBitisYili")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MarkaId");

                    b.ToTable("Modeller", (string)null);
                });

            modelBuilder.Entity("AracIlan.Alan.Varliklar.ModelPaketi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BaslangicYili")
                        .HasColumnType("int");

                    b.Property<int>("BitisYili")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.ToTable("ModelPaketleri", (string)null);
                });

            modelBuilder.Entity("AracIlan.Alan.Varliklar.MotorSecenegi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Guc")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModelPaketiId")
                        .HasColumnType("int");

                    b.Property<int?>("MotorHacmi")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.Property<string>("YakitTipi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ModelPaketiId");

                    b.ToTable("MotorSecenekleri", (string)null);
                });

            modelBuilder.Entity("AracIlan.Alan.Varliklar.UyelikPaketi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("IlanHakki")
                        .HasColumnType("int");

                    b.Property<int>("IlanSuresiGun")
                        .HasColumnType("int");

                    b.Property<int>("MaksimumFotograf")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.Property<int>("Sira")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UyelikPaketleri", (string)null);
                });

            modelBuilder.Entity("AracIlan.Alan.Varliklar.Arac", b =>
                {
                    b.HasOne("AracIlan.Alan.Varliklar.MotorSecenegi", "MotorSecenegi")
                        .WithMany()
                        .HasForeignKey("MotorSecenegiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MotorSecenegi");
                });

            modelBuilder.Entity("AracIlan.Alan.Varliklar.AracGorseli", b =>
                {
                    b.HasOne("AracIlan.Alan.Varliklar.Arac", "Arac")
                        .WithMany("Gorseller")
                        .HasForeignKey("AracId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arac");
                });

            modelBuilder.Entity("AracIlan.Alan.Varliklar.ExpertizRaporu", b =>
                {
                    b.HasOne("AracIlan.Alan.Varliklar.Arac", "Arac")
                        .WithOne("ExpertizRaporu")
                        .HasForeignKey("AracIlan.Alan.Varliklar.ExpertizRaporu", "AracId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arac");
                });

            modelBuilder.Entity("AracIlan.Alan.Varliklar.KullaniciAboneligi", b =>
                {
                    b.HasOne("AracIlan.Alan.Varliklar.UyelikPaketi", "UyelikPaketi")
                        .WithMany()
                        .HasForeignKey("UyelikPaketiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UyelikPaketi");
                });

            modelBuilder.Entity("AracIlan.Alan.Varliklar.Model", b =>
                {
                    b.HasOne("AracIlan.Alan.Varliklar.Marka", "Marka")
                        .WithMany("Modeller")
                        .HasForeignKey("MarkaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Marka");
                });

            modelBuilder.Entity("AracIlan.Alan.Varliklar.ModelPaketi", b =>
                {
                    b.HasOne("AracIlan.Alan.Varliklar.Model", "Model")
                        .WithMany("Paketler")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("AracIlan.Alan.Varliklar.MotorSecenegi", b =>
                {
                    b.HasOne("AracIlan.Alan.Varliklar.ModelPaketi", "ModelPaketi")
                        .WithMany("MotorSecenekleri")
                        .HasForeignKey("ModelPaketiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ModelPaketi");
                });

            modelBuilder.Entity("AracIlan.Alan.Varliklar.Arac", b =>
                {
                    b.Navigation("ExpertizRaporu");

                    b.Navigation("Gorseller");
                });

            modelBuilder.Entity("AracIlan.Alan.Varliklar.Marka", b =>
                {
                    b.Navigation("Modeller");
                });

            modelBuilder.Entity("AracIlan.Alan.Varliklar.Model", b =>
                {
                    b.Navigation("Paketler");
                });

            modelBuilder.Entity("AracIlan.Alan.Varliklar.ModelPaketi", b =>
                {
                    b.Navigation("MotorSecenekleri");
                });
#pragma warning restore 612, 618
        }
    }
}
